Repository maple-labs/erc20, pull requests merged in 2022-03, with the labels that each got.

#13 feat: Add permit functionality (SC-4847)
  contracts/ERC20Permit.sol
  contracts/interfaces/IERC20Permit.sol
  contracts/test/ERC20.t.sol
  contracts/test/ERC20Permit.t.sol
  contracts/test/accounts/ERC20User.sol
  contracts/test/mocks/MockERC20.sol
Labels: Priority: High, Status: Revisions Needed

#17 feat: Update ERC20Permit test to not use MockERC20Permit
  contracts/test/ERC20Permit.t.sol
Labels: Priority: High, Status: Ready for Review

#18 feat: Update ERC20Permit test for inheritance
  contracts/test/ERC20Permit.t.sol
Labels: Priority: High, Status: Ready for Review

#22 chore: Reorder internals to be alphabetical
  contracts/ERC20.sol
  contracts/ERC20Permit.sol
Labels: Priority: High, Status: Ready for Review

#23 feat: Convert DOMAIN_SEPARATOR to view function (SC-4960)
  contracts/ERC20Permit.sol
  contracts/interfaces/IERC20Permit.sol
Labels: Priority: Medium, Status: Ready for Review

#24 feat Consolidate logic (SC-5004)
  README.md
  contracts/ERC20.sol
  contracts/ERC20Permit.sol
  contracts/interfaces/IERC20.sol
  contracts/interfaces/IERC20Permit.sol
  contracts/test/ERC20.t.sol
  contracts/test/ERC20Permit.t.sol
  contracts/test/accounts/ERC20User.sol
  contracts/test/mocks/MockERC20.sol
  contracts/test/utils/InvariantTest.sol
  contracts/test/utils/Vm.sol
Labels: Priority: High, Status: Ready for Review

#26 fix: Fix malleable signature (SC-5066)
  contracts/ERC20.sol
  contracts/test/ERC20.t.sol
Labels: Priority: High, Status: Ready for Review

#25 fix: Update README
  README.md
Labels: Priority: High, Status: Ready for Review

#29 feat: `unchecked` gas savings (SC-5161)
  contracts/ERC20.sol
Labels: Priority: High, Status: Ready for Review

#28 fix: test_permitBadV
  contracts/test/ERC20.t.sol
Labels: Priority: High, Status: Ready for Review

#31 chore: Standardization and cleanup
  contracts/ERC20.sol
  contracts/interfaces/IERC20.sol
  contracts/test/ERC20.t.sol
  contracts/test/accounts/ERC20User.sol
  contracts/test/mocks/MockERC20.sol
Labels: Priority: Medium, Status: Ready for Review

#32 fix: public tests
  contracts/test/ERC20.t.sol
Labels: Priority: Medium, Status: Ready for Review

#33 feat: Add ASCII art
  contracts/ERC20.sol
Labels: Priority: High, Status: Ready for Review

#35 fix: C4 - Use fixed pragma (SC-5353)
  contracts/ERC20.sol
  contracts/interfaces/IERC20.sol
  contracts/test/ERC20.t.sol
  contracts/test/accounts/ERC20User.sol
  contracts/test/mocks/MockERC20.sol
Labels: Status: Ready for Review

#36 fix: C4 - Fix typos (SC-5350)
  contracts/interfaces/IERC20.sol
Labels: Status: Ready for Review

#37 fix: Update `PERMIT_TYPEHASH` to be in accordance with ERC-2612 (SC-5345)
  contracts/ERC20.sol
  contracts/test/ERC20.t.sol
Labels: Priority: Low, Status: Ready for Review

#38 feat: Implement infinite approval (SC-5372)
  contracts/ERC20.sol
  contracts/test/ERC20.t.sol
Labels: Priority: High, Status: Ready for Review
